### ISSUE TITLE
Tests for platforms without fenv.h

### ISSUE THREAD

**Issue by tdaede** [picolibc/picolibc#102]
I'm working on adding build and test support for m68k, which doesn't have a newlib sys/fenv.h header (and therefore no FE exception support). This works on newlib because all newlib tests check for the presence of FE_INVALID etc. I was wondering if this is the approach you would like to take on picolibc as well before I plow ahead, with the caveat that it will result in a lot of ifdefs in math_errhandling_tests.c.

**Comment by keith-packard** [comment]
I *think* everything except that one test program should build without new ifdefs. I should have written the new test to run on machines without fenv.h, but I was focused on getting the fenv stuff working correctly. Feel free to hack up that test to make it build for you.

**Comment by keith-packard** [comment]
This should all work correctly now -- there's a default fenv.h which defines the few required macros (like FE_ALL_EXCEPT) to let applications know they aren't getting any useful fenv support.
