### ISSUE TITLE
PRINTF_LONGLONG cannot apply when printf supports double?

### ISSUE THREAD

**Issue by alister-f** [picolibc/picolibc#167]
In newlib\libc\tinystdio\vfprintf.c, it is only defined when "#if PRINTF_LEVEL == PRINTF_STD || PRINTF_LEVEL == PRINTF_FLT"

**Comment by keith-packard** [comment]
PRINTF_FLT is set for both the float version and the double version of printf, so you always get LONGLONG support with either float version.
