### ISSUE TITLE
picolibc build error

### ISSUE THREAD

**Issue by silicongarage** [picolibc/picolibc#174]
I'm trying to build picolibc under Mac OS 11.5 and need a little help with an error I get when running
"scripts/do-arm-configure"

I have looked through through all the config files trying to understand how to fix the following error message:

../meson.build:388:0: ERROR: "install_dir" must be specified when "install" in a configure_file is true

I’m pretty sure it’s simple once I know where to look. 

Thanks!

**Comment by keith-packard** [comment]
Ah, Mac OS X has a version of 'expr' which doesn't support the substr operator. I've applied a patch and it's waiting to get tested. Thanks for finding this bug!
