### ISSUE TITLE
Where should __assert_func() be located?

### ISSUE THREAD

**Issue by yashi** [picolibc/picolibc#237]
This is related to #177.

Where should we put `__assert_func()`? Under Zephyr or picolibc?  Or perhaps app should have it?  There are a few `__assert_func()` under picolibc.  But I feel like Zephyr should have it as a glue code.  Is it OK for picolibc that if I put the function under Zephyr?

**Comment by keith-packard** [comment]
I can imagine that zephyr would like to replace __assert_func with something that works better in that environment. Any reason picolibc can't continue to provide a default too?

**Comment by yashi** [comment]
Yes, I think Zephyr want to connect to its logging facility.

> Any reason picolibc can't continue to provide a default too?

It can, I suppose.  But, in order to print messages, picolibc must know how to do it.  `printk()`, `printf()`, or `LOG_ERR()`, right?

**Comment by keith-packard** [comment]
for bits inside picolibc, that'd be printf, or perhaps fprintf(stderr, ...). If you want to replace this function in zephyr, then you'd probably want to use LOG_ERR?

**Comment by yashi** [comment]
I'll have it in Zephyr repo.  Thanks.
