### ISSUE TITLE
powerpc: frexpl fails to build

### ISSUE THREAD

**Issue by shenki** [picolibc/picolibc#249]
frexpl.c does not contain an implementation for powerpc's long double format, causing the build to fail:

```
../newlib/libm/common/frexpl.c:128:4: error: #error Unsupported long double format.
  128 | #  error Unsupported long double format.
      |    ^~~~~
```

34876c05a527a7295920979fce69cec6b4cb613c introduced the #error. Reverting this commit allows the build to succeed but I assume does not do the correct thing.

**Comment by keith-packard** [comment]
oops! Build regressions are no fun. The PR fixing this adds build tests to CI to make sure it doesn't break again.
