### ISSUE TITLE
newlib-retargetable-locking is actually enabled by default

### ISSUE THREAD

**Issue by rdiez** [picolibc/picolibc#266]
About this page:

https://github.com/picolibc/picolibc/blob/main/doc/build.md

Section "Locking support" states:

"By default, all of this is disabled as it would require underlying system support."

The table says too:

Option: newlib-retargetable-locking  Default: false

However, in this file:

https://github.com/picolibc/picolibc/blob/main/meson_options.txt

```
option('newlib-multithread', type: 'boolean', value: true,
       description: 'enable support for multiple threads')

option('newlib-retargetable-locking', type: 'boolean', value: true,
       description: 'Allow locking routines to be retargeted at link time')
```

So the default for newlib-retargetable-locking is actually true, and the same holds for newlib-multithread.

**Comment by keith-packard** [comment]
I've gone through build.md to make sure it matches meson_options.txt. I ended up expanding the documentation about locking so that someone would have a chance of building a working implementation.
