### ISSUE TITLE
Meson 0.53.2: Compiler arm-none-eabi-gcc can not compile programs

### ISSUE THREAD

**Issue by eugene-so** [picolibc/picolibc#270]
FYI, I found this issue using meson 0.53.2.  It is fixed in meson 0.54.2, so you might want to update this repo.

---

The Meson build system
Version: 0.53.2
Source dir: /home/eso/build/picolibc
Build dir: /home/eso/build/picolibc/scripts/build-arm
Build type: cross build
Project name: picolibc
Project version: 1.7.6
C compiler for the build machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the build machine: cc ld.bfd 2.34

meson.build:35:0: ERROR: Compiler arm-none-eabi-gcc can not compile programs.

---

Here is a related link that describes the same problem.

https://github.com/mesonbuild/meson/issues/6594

**Comment by keith-packard** [comment]
Did you try adding 'skip_sanity_check=true' to the [properties] section of your cross file?

**Comment by eugene-so** [comment]
Yes this property was present when the error occurred.

**Comment by keith-packard** [comment]
argh. so we can only use the simpler exe-wrapper on newer versions of meson. That's super helpful. I guess we can either revert the exe-wrapper change or bump the required version of meson. I think I can come up with a version that is only a bit more complicated than the current one, but not as complicated as the original one.

**Comment by keith-packard** [comment]
If you can give PR #271 a try (branch meson-53-support) to verify whether I'm correct about the failure, that would be super helpful.

**Comment by eugene-so** [comment]
The failure still occurs: 

eso@eso-OptiPlex-7080:~/build/picolibc/scripts/build-arm$ ../do-arm-configure -Dc_std=c99
The Meson build system
Version: 0.53.2
Source dir: /home/eso/build/picolibc
Build dir: /home/eso/build/picolibc/scripts/build-arm
Build type: cross build
Project name: picolibc
Project version: 1.7.6
C compiler for the build machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the build machine: cc ld.bfd 2.34

meson.build:35:0: ERROR: Compiler arm-none-eabi-gcc can not compile programs.

A full log can be found at /home/eso/build/picolibc/scripts/build-arm/meson-logs/meson-log.txt
eso@eso-OptiPlex-7080:~/build/picolibc/scripts/build-arm$ git status
On branch meson-53-support

**Comment by keith-packard** [comment]
Thanks. I created a python venv to install meson 0.53.2 and reproduced your issue. The fix is to re-add the `-nostdlib` option in the compiler configuration in the cross file as meson 0.53.2 doesn't use any other c flags for early compiler tests. I pushed this change to the meson-53-support branch.
