### ISSUE TITLE
linking against picolib gives some undefined references

### ISSUE THREAD

**Issue by basprins** [picolibc/picolibc#291]
Hi,

I just managed to compile picolib, with everything set to default.

when I try to compile my program with picolib iso libc_nano, I get the following linker errors:

```
/usr/local/mcuxpressoide-11.5.1_7266/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.1.202201181444/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /usr/local/picolibc/arm-none-eabi/lib/thumb/v8-m.main+fp/hard/libc.a(libc_stdlib_assert.c.o): in function `__assert_func':
/home/bp/dev/picolibc/build/../newlib/libc/stdlib/assert.c:62: undefined reference to `stderr'
/usr/local/mcuxpressoide-11.5.1_7266/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.1.202201181444/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /usr/local/picolibc/arm-none-eabi/lib/thumb/v8-m.main+fp/hard/libc.a(libc_tinystdio_printf.c.o): in function `printf':
/home/bp/dev/picolibc/build/../newlib/libc/tinystdio/printf.c:46: undefined reference to `stdout'
/usr/local/mcuxpressoide-11.5.1_7266/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.1.202201181444/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /usr/local/picolibc/arm-none-eabi/lib/thumb/v8-m.main+fp/hard/libc.a(libc_signal_signal.c.o): in function `raise':
/home/bp/dev/picolibc/build/../newlib/libc/signal/signal.c:132: undefined reference to `getpid'
/usr/local/mcuxpressoide-11.5.1_7266/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.1.202201181444/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /home/bp/dev/picolibc/build/../newlib/libc/signal/signal.c:132: undefined reference to `kill'
/usr/local/mcuxpressoide-11.5.1_7266/ide/plugins/com.nxp.mcuxpresso.tools.linux_11.5.1.202201181444/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /usr/local/picolibc/arm-none-eabi/lib/thumb/v8-m.main+fp/hard/libc.a(libc_stdlib_abort.c.o): in function `abort':
/home/bp/dev/picolibc/build/../newlib/libc/stdlib/abort.c:63: undefined reference to `_exit'
```

I read something on the wiki about having to define my own `FILE *stdout` etc. Not sure where I should define them. 

Also I seem to miss the implementation of `getpid`, and `_exit`. Not an expert on this either, is this typically part of the stdlib? Should I be able to find this in my arm toolchain?

**Comment by basprins** [comment]
Aha, seems that I compiled with semihosting enabled. I didn't want that :). 

Adding libsemshosting.a solved the problem for now, will rebuild the lib without semihosting

**Comment by keith-packard** [comment]
The C standard defines the `abort` function in terms of the `raise` function, while the POSIX standard defines the `raise(sig)` function as equivalent to `kill(getpid(), sig)`. Picolibc implements these as specified, with `abort` having a backup call to `_exit` in case `raise` returns (it shouldn't, so this call could be removed). That means if your application calls `abort`, you end up with `_exit`, `getpid` and `kill` as undefined references.

`stdin`, `stdout` and `stderr` are used by tinystdio and other parts of the library for communicating with the environment. You'll want to define these with hooks to whatever console implementation you have.

All of these picolibc details are covered in the [picolibc os docs](https://github.com/picolibc/picolibc/blob/main/doc/os.md)
