### ISSUE TITLE
Default newlib elix mismatch with picolibc

### ISSUE THREAD

**Issue by DFOVIT** [picolibc/picolibc#295]
I think that the meaning of the enable-newlib-elix-level option in picolibc differs from the one in newlib.
In newlib when enable-newlib-elix-level is not defined or set to 0 it will build the libc with level 4 elix functions (as seen here [newlib sourceware](https://sourceware.org/git?p=newlib-cygwin.git;a=blob;f=newlib/libc/stdio/Makefile.inc;h=2126ceaf591164a19c5cb1eb000e7b7b658462e7;hb=HEAD#l141)).
In picolib  when enable-newlib-elix-level is not defined, it will build the libc without elix level 4 functions ([picolibc](https://github.com/picolibc/picolibc/blob/main/newlib/libc/stdio/meson.build#L219))

**Comment by keith-packard** [comment]
I hadn't ever really looked into what ELIX meant, or how it was supposed to work. It looks like it should just be set to 4 by default, and perhaps allow users to set it to a different level? Given how little of the library bothers to even look at the value, I'm tempted to just remove the configuration option and set it to 4?

**Comment by keith-packard** [comment]
fwiw, the default value in picolibc appears to be '2'. Would just changing the default to '4' suffice?

**Comment by keith-packard** [comment]
oh, and the _ELIX_LEVEL value is never set, so any code which depends on that will not see the specified value.

**Comment by DFOVIT** [comment]
Yes it seems reasonable to set the default to 4.

**Comment by keith-packard** [comment]
Now to fix the newlib code so that it actually builds with warnings enabled.

**Comment by keith-packard** [comment]
This was fixed in #296
