### ISSUE TITLE
picolibc.spec has wrong path for crt0 with "multilib=false"

### ISSUE THREAD

**Issue by ThyMYthOS** [picolibc/picolibc#308]
With the following steps:
```
mkdir build-nomultilib
cd build-nomultilib
../scripts/do-rv32imac-configure -Dprefix=$PWD/../install -Dspecsdir=$PWD/../install -Dmultilib=false
ninja
ninja install
```
We get a spec file that searches crt0 in `install/picolibc/rv32imac/lib/rv32imac/ilp32/crt0.o` but it is actually in `install/picolibc/rv32imac/lib/crt0.o`.

**Comment by keith-packard** [comment]
oh, looks like non-multilib installs need to remove the %M from the paths in the .specs files?
