### ISSUE TITLE
malloc.h uses defines present in cdefs.h but it doesn't include cdefs.h

### ISSUE THREAD

**Issue by AntonioND** [picolibc/picolibc#432]
`stdlib.h` includes `<sys/cdefs.h>` correctly:

https://github.com/picolibc/picolibc/blob/74aded414df7b0d27b88af5934c1047b8f28435e/newlib/libc/include/stdlib.h

However, `malloc.h` doesn't, which makes including `malloc.h` generate a build error because it can't find `_malloc_like` and things like that.

https://github.com/picolibc/picolibc/blob/74aded414df7b0d27b88af5934c1047b8f28435e/newlib/libc/include/malloc.h

**Comment by keith-packard** [comment]
Looks like malloc.h needs sys/cdefs.h.
