### ISSUE TITLE
Wrong result in floor

### ISSUE THREAD

**Issue by 8U61ife** [picolibc/picolibc#480]
The comparison at L107 should be an unsigned compare. But in commit f306135, the variable j change to a signed integer. 
https://github.com/picolibc/picolibc/blob/d07c38ff051386f8e09a143ea0a6c1d6d66dd1d8/newlib/libm/math/s_floor.c#L98-L111

Example:
Consider a double in value -0x1.fffffcp+21.
The lsw of double(variable i1) is 0xc0000000.
The variable j = 0xc0000000 + (1 << (52 - 21)) = 0x40000000
There is a carry in this case.
"j < i1" is equal to "0x40000000 < 0xc0000000". Carry only detect by an unsigned compare.

**Comment by keith-packard** [comment]
Nice one! There's a matching bug in ceil too. Fix (and test cases) coming shortly.
