### ISSUE TITLE
Optionally dropping error messages in strerror()

### ISSUE THREAD

**Issue by rdiez** [picolibc/picolibc#491]
File newlib/libc/string/strerror.c defines a lot of error messages, most of which will never be used in tight embedded environments. For example, who needs ELIBEXEC ("Cannot exec a shared library directly") in a bare-metal firmware?

I have patched Newlib to get rid of them:

https://github.com/rdiez/DebugDue/blob/master/Toolchain/Patches/NewlibRemoveStrerrorMessages.patch

I can do the same with Picolibc, but I am wondering whether Picolibc should provide an option to do this itself. I am guessing other people may need to save space even if some shared routines do call strerror().

**Comment by keith-packard** [comment]
It would certainly be reasonable to provide three modes when building the library -- C mode (which requires only three errno values), POSIX mode (which has the list defined here (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html) and "extended" mode which provides the current list.

Or even a mode where the function doesn't have any pre-defined strings and just uses `sprintf()` into a thread-local static buffer?

In any case, as with all C library functions, you can replace this function with one of your own making.
