### ISSUE TITLE
CMake build system should generate a libm stub.  

### ISSUE THREAD

**Issue by BlamKiwi** [picolibc/picolibc#493]
As title, I only see a call to `add_library(c STATIC)`. Clang/lld will automatically specify `-lm`, breaking the build.

**Comment by keith-packard** [comment]
Just so you know -- the cmake build system is really only designed to support Zephyr's use as a module and not as a general purpose method for building the library. So, if this isn't related to use of picolibc as a Zephyr module, then it's not really useful to fix it.

**Comment by BlamKiwi** [comment]
No problem, don't worry about it then.
