### ISSUE TITLE
[Semihosting] Automatic inclusion of 'program-name' does not work with qemu without args

### ISSUE THREAD

**Issue by joe-img** [picolibc/picolibc#516]
Hi,

The qemu option `-semihosting-config arg=...` is used to pass command line arguments.
Picolibc automatically adds `"program-name"` as the first argument.

For example `-semihosting-config arg="hello world"` would result in three arguments:
```
Arg 0: program-name
Arg 1: hello
Arg 2: world
```

However, when `arg=...` is **not** supplied, qemu automatically adds the program name, so the output would look like:
```
Arg 0: program-name
Arg 1: test.elf
```
This can break some assumptions when parsing command line arguments.

I don't know where the issue is here, I can see two ways forward:
1) Remove picolibc's default "program-name" and submit a patch to qemu to add the program name as the first argument when args are suppleid
2) Remove picolibc's default "program-name" and change the run scripts to pass the program name as the first argument manually.

I'm happy to try and write the patch.

Thanks!

**Comment by keith-packard** [comment]
Closed by #517
