### ISSUE TITLE
Undefined symbol strtoumax_l

### ISSUE THREAD

**Issue by stuarch** [picolibc/picolibc#52]
As title.
I think it just has a wrong function name in strtoumax.c

I built picolibc for risc-v with:
```
-Dnewlib-nano-malloc=true
-Dnewlib-wide-orient=false
-Dlite-exit=true
-Dnewlib-fvwrite-in-streamio=true
-Dnewlib-elix-level=2
-Dthread-local-storage=false
-Dnewlib-io-float=true         
-Dnewlib-io-long-double=false
-Dnewlib-nano-formatted-io=true
-Dnewlib-tinystdio=false
```

**Comment by keith-packard** [comment]
Thanks for figuring this out! I appear to have missed fixing only one of these function names. I've pushed a fix for this to the main branch.
