### ISSUE TITLE
Request to amend 1.8.3 release to have gnu-arm-toolchain/12.3 prebuilt

### ISSUE THREAD

**Issue by kammce** [picolibc/picolibc#533]
The prebuilt in question is: https://keithp.com/picolibc/dist/gnu-arm-embedded/picolibc-1.8.3-12.3-rel1.zip

I'm working on adding gnu-arm-toolchain to the C/C++ package manager Conan, see [PR](https://github.com/conan-io/conan-center-index/pull/17528). I would also like to add picolibc to this as well before this PR is merged. Using github releases is convenient because the download speeds are faster and more distributed than that of keithp.com servers. I also don't want to completely slam your server. I also cannot use my own github releases because Conan favors getting binaries and packages from the source/creators.

**Comment by keith-packard** [comment]
like this https://github.com/picolibc/picolibc/releases/download/1.8.3/picolibc-1.8.3-12.3-rel1.zip ? Sorry I forgot to upload that during the release; I was on a sketchy connection and getting bits from the build machine to github is tricky.

**Comment by kammce** [comment]
Yes! Thank you! 

And also, thank you for this awesome library! Seeing my binary go from 21kB to 6.2kB and my upload speeds jump up has been an awesome experience!
