### ISSUE TITLE
Arrays in libm tests exceed max object size

### ISSUE THREAD

**Issue by pjonsson** [picolibc/picolibc#540]
Getting some warnings about arrays exceeding max object sizes when trying to compile the tests:
```
../picolibc/newlib/libm/test/conv_vec.c:23:13: warning: size of 'doubles' 51310 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   23 | double_type doubles[] =
      |             ^~~~~~~
./picolibc/newlib/libm/test/atan2_vec.c:18:16: warning: size of 'atan2_vec' 48030 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   18 |  one_line_type atan2_vec[] = {
      |                ^~~~~~~~~
./picolibc/newlib/libm/test/atan2f_vec.c:18:16: warning: size of 'atan2f_vec' 48030 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   18 |  one_line_type atan2f_vec[] = {
      |                ^~~~~~~~~~
../picolibc/newlib/libm/test/iconv_vec.c:20:10: warning: size of 'ints' 39202 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   20 | int_type ints[]={
      |          ^~~~
../picolibc/newlib/libm/test/sprint_vec.c:19:20: warning: size of 'sprint_doubles' 63648 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   19 | sprint_double_type sprint_doubles[] =
      |                    ^~~~~~~~~~~~~~
../picolibc/newlib/libm/test/sprint_ivec.c:19:17: warning: size of 'sprint_ints' 40056 bytes exceeds maximum object size 32767 [-Wlarger-than=]
   19 | sprint_int_type sprint_ints[] =
      |                 ^~~~~~~~~~~
```
Edit: found two more, from other parts of the code:
```
In file included from ../picolibc/test/test-fma.c:120:
../picolibc/test/fma_vec.h:5327:1: error: size of array is too large
 5327 | };
      | ^
../picolibc/test/fma_vec.h:10653:1: error: size of array is too large
10653 | };
      | ^
```

**Comment by keith-packard** [comment]
There's no easy fix for these -- we could stick the test vectors in a file and read them in at runtime, but some targets don't have any file access. The math tests, in particular, pull everything into a single binary, which is probably going to be too large even without the test data.

As a short-term fix, we could add a configuration option that simply disables any tests which are expected to be 'large'.

After that, look into splitting the math tests into per-function tests and maybe consider how we might be able to load them at runtime for targets with file system access.

**Comment by pjonsson** [comment]
I'm still faced with a wall of errors, so I haven't gotten to the part where I figure out how the tests are wired together. With that said, would it be possible to ifdef different parts of the array and compile each source file to multiple binaries, but with a varying define (so sprint_vec-0 is `gcc -DPART0 sprint_vec.c -o sprint-vec-0`, sprint_vec-1 is `gcc -DPART1 sprint_vec.c -o sprint-vec-1` and so on)? For large architectures, it will obviously not be ideal to chunk the test data into 4k clumps, but it's hard to fit a large array in 8k RAM.

I don't know meson though, so if adding a switch to ignore things is easy, I'm happy with that as well.

**Comment by keith-packard** [comment]
Good thinking to try and split the arrays into multiple test apps instead of just not running some of them. Yes, that's certainly easy to do. In the meson.build file, you'll see this little piece:
```
  test(test_name,
       executable(test_name, math_test_src,
		  c_args: _c_args,
		  objects: objs,
		  link_with: libs,
		  link_args: _link_args,
		  link_depends: _link_depends,
		  include_directories: inc),
       depends: bios_bin,
       env: test_env)
```
You can add a per-executable define by appending it to the `c_args` piece there, if you changed that to `c_args: _c_args + ['-DTEST_PART=0']`, you'd then be able to check for `#if TEST_PART == 0` in the source code. Then you just need multiple blocks like this to create multiple tests. You'd need to create custom names for the test and the executable (they can be the same). You could even do that automatically within a foreach loop.

**Comment by pjonsson** [comment]
I pushed a draft for the split in #550, was that along the lines of what you had in mind?

The draft makes the object files build, but the usual linker error when running out of space still appears since multiple tests still end up in the same executable. Still, I think that error message is more familiar to MSP430 users than too large object sizes.

There are still a couple of large arrays left, for example, conv_vec.c contains:

```C
#ifndef __PCCNECV70__
/* Nec assembler has built in limits which are exceeded by this table */
```

which would nest the ifdefs. The ifndef is from 2000, is the platform that uses "Nec assembler" still a supported target, or could it just be removed?

**Comment by keith-packard** [comment]
Tests are running on MSP430. They're still not able to fit in 64kB, but that's a "simple" matter of additional factoring and splitting.
