### ISSUE TITLE
error: "INFINITY" redefined

### ISSUE THREAD

**Issue by hoxi** [picolibc/picolibc#647]
I'm trying to compile picolibc using arm-none-eabi (13.2) and end up with the following compilation error:

```
/home/magnus/testbuild/picolibc/newlib/libc/posix/utils.h:39: error: "INFINITY" redefined [-Werror]
   39 | #define INFINITY        (DUPMAX + 1)
      | 
In file included from /home/magnus/testbuild/build/picolibc/picolibc/include/sys/config.h:34,
                 from /home/magnus/testbuild/build/picolibc/picolibc/include/_ansi.h:44,
                 from /home/magnus/testbuild/build//picolibc/picolibc/include/sys/types.h:48,
                 from /home/magnus/testbuild/picolibc/newlib/libc/posix/regerror.c:43:
/proj/gcc_arm/11_2023_13.2/lib/gcc/arm-none-eabi/13.2.1/include/float.h:262: note: this is the location of the previous definition
  262 | #define INFINITY        (__builtin_inff ())
      | 
```
Seems like the 'utils.h' #define of INFINITY conflicts with ARM gcc found in 'float.h' (which is included via a chain from regerror.c).

I could fix it by just remove the definition in utils.h (and add two explicit casts in regerror.c). But could this be fixed in a better way?

**Comment by keith-packard** [comment]
whoa. that's a bug. It's a magic value for the regex code, so it has to be an int. I'd suggest renaming it to REGEX_INFINITY or some such (naming is hard). It looks like the only place it occurs is in libc/posix/regcomp.c?
