### ISSUE TITLE
zephyr: zephyr.cmake: _POSIX_C_SOURCE should be defined in Zephyr

### ISSUE THREAD

**Issue by cfriedt** [picolibc/picolibc#649]
I hate being pedantic, but the spec says that this should be `200809L` (rather than `200809`).

https://github.com/picolibc/picolibc/blob/a97720d2a6970239b1dd3936685a372f13303339/zephyr/zephyr.cmake#L96

In any case, Zephyr might need to commandeer this declaration (i.e. get it removed from picolibc), since it conflicts with Zephyr's [LTSv3 POSIX API Roadmap](https://github.com/zephyrproject-rtos/zephyr/issues/51211). Zephyr will need to have control over the feature test macros ultimately.

**Comment by keith-packard** [comment]
Oh, Zephyr shouldn't need this anymore either -- picolibc should be exposing the complete Zephyr C Library API without any extra defines needed.
