### ISSUE TITLE
[CMake] Not does not not, breaks printf

### ISSUE THREAD

**Issue by ekliptik** [picolibc/picolibc#662]
While I'm now aware that CMake is a 2nd-tier / legacy build system here, there is enough of a sneaky problem here to warrant a fix:

https://github.com/picolibc/picolibc/blob/1b0731fc9a3cd0a18d81768982e99461b13c0341/CMakeLists.txt#L422

Ignore the LSP highlighting "NOT" as a magic keyword. This statement doesn't complement the variable. Instead, it appends "NOT" to the variable, which causes it to always evaluate as true. This caused printf to break due to multiple implementations aliasing to `vfprintf`. To demonstrate:

`message("CMAKE says " ${FORMAT_DEFAULT_MINIMAL}"_"${FORMAT_DEFAULT_DOUBLE}"_"${FORMAT_DEFAULT_FLOAT}"_"${FORMAT_DEFAULT_INTEGER}"_"${FORMAT_DEFAULT_LONG_LONG})`

prints `CMAKE says "_"1"_"0"_"NOT1"_"0`

Replacing the clause like so:
```diff
 if(NOT DEFINED FORMAT_DEFAULT_INTEGER)
-  set(FORMAT_DEFAULT_INTEGER NOT ${__IO_FLOAT})
+  if(NOT __IO_FLOAT)
+      set(FORMAT_DEFAULT_INTEGER TRUE)
+  else()
+      set(FORMAT_DEFAULT_INTEGER FALSE)
+  endif()
 endif()
```

makes that `message` statement print `CMAKE says "_"1"_"0"_"FALSE"_"0` which is functionally correct. I hope there's a neater solution, hence no PR.

**Comment by keith-packard** [comment]
Thanks for the report; that's definitely broken, and something I've learned about cmake in the last couple of years since I wrote that. I don't know of a better solution than the one you've propose. I've fixed the tests to check this and pushed those changes along with a fix modeled on this plan.
