### ISSUE TITLE
ld.lld: error: undefined symbol: _impure_ptr

### ISSUE THREAD

**Issue by kaishaoshao** [picolibc/picolibc#736]
I compiled the riscv version of libc library and libsemihost library, and then compiled the test program in test, and found that for stdout/stdin... How to solve this error

**Comment by kaishaoshao** [comment]
This is because picolibc and newlib implement stdout/stdin differently. When using the compiler, if it defaults to newlib files, it will get this error.

**Comment by begriffs** [comment]
Related issue on arm - https://github.com/picolibc/picolibc/issues/38#issuecomment-2290560039
