### ISSUE TITLE
qemu-system-riscv32 does not support semihostconfig

### ISSUE THREAD

**Issue by elliott-wen** [picolibc/picolibc#75]
Hi, when I tried to run qemu-system-riscv32 to simulate the hello-world program, I got the following error

qemu-system-riscv32: -semihosting-config chardev=stdio0: Option not supported for this target

At the very beginning, I though it's because of my old qemu version. But after trying the latest qemu 5.1 release, I still got the same error. Do you apply some magic patches on your qemu?

Cheers

**Comment by archi** [comment]
Hi @elliott-wen, try using Keith's `riscv-semihost` qemu branch at https://github.com/keith-packard/qemu/tree/riscv-semihost - this worked for me.

**Comment by elliott-wen** [comment]
thanks for pointing that out.
 Cheers

**Comment by keith-packard** [comment]
I've been asking for this to be merged upstream, but so far it hasn't happened.
