### ISSUE TITLE
The latest release   undefined reference to `stdout'

### ISSUE THREAD

**Issue by yy172** [picolibc/picolibc#757]
Hello, I have a usage question. I downloaded the latest release version, unzipped it and put it in the toolchain arm-none-elf-gcc 13.2 directory, and compiled the code with the following parameters "arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -mthumb-interwork -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -g -T "test.ld" -Xlinker --gc-sections -specs=picolibc.specs". When linking, an error is reported: " toolchain/arm-none-eabi-gcc/bin/../arm-none-eabi/picolibc/arm-none-eabi/lib/thumb/v7-m/nofp\libc.a(libc_tinystdio_printf.c.o): in function `printf':
/build/picolibc/builds/build-arm-tk-minsize/../../newlib/libc/tinystdio/printf.c:45:(.text.printf+0x20): undefined reference to `stdout'", what is causing this?

**Comment by keith-packard** [comment]
You need to define stdout to suit your particular environment. Check out the docs: https://github.com/picolibc/picolibc/blob/main/doc/os.md and see if that helps you understand how to make this work. There are samples for several targets in the semihost tree.
