### ISSUE TITLE
Build race when building tests

### ISSUE THREAD

**Issue by arichardson** [picolibc/picolibc#814]
I updated my picolibc checkout today and got the following error:
`error: no such file or directory: '$HOME/build/picolibc-arm32-build/newlib/libc.a'` when building the tests. It sounds like there is a missing dependency here?

Retrying a few times eventually allows the build to succeed.

**Comment by keith-packard** [comment]
Yeah, I was noticing similar issues. Bisecting to figure out where it broke is probably indicated. I'm flying rockets for the next week and won't be able to get to figuring this out until I'm back home though.

**Comment by keith-packard** [comment]
Ok, I've got a patch merged which should help. Please see if #824 had any effect for you. I probably should have tied this issue to that PR, but I wasn't sure it was the same issue.

**Comment by arichardson** [comment]
The build now works for me, so I imagine https://github.com/picolibc/picolibc/pull/824 fixed the issue. Thanks!
