### ISSUE TITLE
[Bug?] `__IMPORT` leftover

### ISSUE THREAD

**Issue by elpekenin** [picolibc/picolibc#835]
I see that `__IMPORT`/`__EXPORT` macros were removed from the codebase with bd3ad599b0d610fed8468d996306f15e3400b938

However, there are still 2 occurrences of it here: https://github.com/picolibc/picolibc/blob/main/newlib/libc/include/unctrl.h#L39-L40

Im not too familiar with the codebase, and maybe these are needed for compatibility with some platform or library... But im guessing they just flew under the radar during removal

**Comment by keith-packard** [comment]
Yup, thanks for finding this.
