### ISSUE TITLE
fflush(stdio) causes null dereference

### ISSUE THREAD

**Issue by denizzzka** [picolibc/picolibc#86]
(fflush code provided by tinystdio)

`fflush(stdout);` on semihosting causes null dereference.

I think in case stdout isn't supports flush some check must be used inside of fflush?

**Comment by keith-packard** [comment]
I can't make this fail -- I hacked up the 'hello-world' example and added fflush(stdout) after the printf call and it seems to work fine. Got a more complete example that does fail?

**Comment by denizzzka** [comment]
Confirmed, false-positive. I accidentally used another pointer as stdout in my code.

**Comment by keith-packard** [comment]
Thanks for checking! Always nice to figure out why something crashed.
