### ISSUE TITLE
memcpy assumes unaligned access for armv7a aligned targets

### ISSUE THREAD

**Issue by pratlucas** [picolibc/picolibc#865]
We've hit an issue in [ARM-software/LLVM-embedded-toolchain-for-Arm](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm) when trying to build a version of picolibc for armv7a using `-mno-unaligned-access`, where a data abort is triggered by memcpy.

Currently, for armv7a targets, the wrapper used to choose a memcpy implementation uses `memcpy-v7a.S` for unaligned targets and `aeabi_memcpy-v7a.S` for aligned targets:
https://github.com/picolibc/picolibc/blob/1c73900b79dbc02b80d09f5d637382249158e1ec/newlib/libc/machine/arm/memcpy.c#L34-L45

However, the implementation in `aeabi_memcpy-v7a.S` also assumes unaligned accesses are supported by the target:
https://github.com/picolibc/picolibc/blob/1c73900b79dbc02b80d09f5d637382249158e1ec/newlib/libc/machine/arm/aeabi_memcpy-armv7a.S#L209-L242

The fix appears to be to update the conditions in `newlib/libc/machine/arm/memcpy.c` to fallback to the implementation from `string/memcpy.c` when `__ARM_FEATURE_UNALIGNED` is defined. This leaves `aeabi_memcpy-v7a.S` without much use, though, and I couldn't spot any other conditions for it to be chosen.

I'm happy to submit a PR with the fix described above, but I'd appreciate some guidance on what to do regarding `aeabi_memcpy-v7a.S` if possible. Are there any scenarios where this implementation would be preferable? And if not, would the correct approach be to remove it completely?

**Comment by pratlucas** [comment]
For reference, newlib appears to guard the use `aeabi_memcpy-v7a.S` under `defined (__ARM_FEATURE_UNALIGNED)`:

https://sourceware.org/git/?p=newlib-cygwin.git;a=blame;f=newlib/libc/machine/arm/aeabi_memcpy.c;hb=a015d9b507402823bc80e1dd452be692d672a9c7#l43

**Comment by keith-packard** [comment]
It looks like aeabi_memcpy-armv7a.S tries to avoid unaligned access. Is it just broken? Would it be easy to fix?

**Comment by keith-packard** [comment]
#866 was the simplest fix I could come up with; obviously a lot more instructions this way.

**Comment by pratlucas** [comment]
Thanks @keith-packard! Apologies for the delay, I got side tracked into other work.

To reproduce the fault in qemu using the LLVM-embedded-toolchain-for-Arm, beyond configuring `SCTLR.A` and `SCTLR.U`, I believe you'll need the changes from llvm/llvm-project#114782 and a new library variant for the matching option:
```cmake
add_library_variants_for_cpu(
    armv7a
    SUFFIX soft_nofp_strictly_aligned
    COMPILE_FLAGS "-mfloat-abi=soft -march=armv7a -mfpu=none -mno-unaligned-access"
    MULTILIB_FLAGS "--target=armv7-unknown-none-eabi -mfpu=none -mno-unaligned-access"
    PICOLIBC_BUILD_TYPE "release"
    QEMU_MACHINE "none"
    QEMU_CPU "cortex-a7"
    QEMU_PARAMS "-m 1G"
    BOOT_FLASH_ADDRESS 0x00000000
    BOOT_FLASH_SIZE 0x1000
    FLASH_ADDRESS 0x20000000
    FLASH_SIZE 0x1000000
    RAM_ADDRESS 0x21000000
    RAM_SIZE 0x1000000
    STACK_SIZE 4K
)
```

You can then use the following reproducer to trigger the data abort:
```c++
#define __STDC_WANT_LIB_EXT1__ 1
#include <stdio.h>
#include <string.h>
int
main(void)
{
    printf("---------Inside Main\n");
    char src[] = "Hello, world!";
    char dest[50];
    printf("---------Starting Normal copy\n");
    memcpy_s(dest, sizeof(dest), src, strlen(src) + 1);
    printf("After memcpy_s Call\n");
    return 0;
}
```
```
$ clang --target=armv7a-none-eabi -march=armv7a -mfpu=none -mfloat-abi=soft -mno-unaligned-access -std=c11 -nostartfiles -lcrt0-semihost -lsemihost -g -T ./ldscripts/microbit.ld memcpy.c -o memcpy-not-working.elf

$ qemu-system-arm -M none -cpu cortex-a9 -m 1G -chardev stdio,mux=on,id=stdio0 -semihosting-config enable=on,chardev=stdio0,arg=program-name -monitor none -serial none -nographic -device loader,file=memcpy-not-working.elf
```
