### ISSUE TITLE
memzero support?

### ISSUE THREAD

**Issue by zhang-wenchao** [picolibc/picolibc#871]
I need to write 0 to memory to prevent leakage in a large number of applications, is there a shortcut to do this, currently I do.

```
void memzero(void *const pnt, const size_t len) {
  volatile unsigned char *volatile pnt_ = (volatile unsigned char *volatile)pnt;
  size_t i = (size_t)0U;

  while (i < len) {
    pnt_[i++] = 0U;
  }
}
```

**Comment by zhang-wenchao** [comment]
maybe trans this to discussions.

**Comment by keith-packard** [comment]
Is there some reason you don't want to use `memset(pnt, 0, len)`?

**Comment by zhang-wenchao** [comment]
Due to compiler optimizations, memset may not guarantee complete memory zeroing, which is critical for secure key erasure in high-security environments.

**Comment by keith-packard** [comment]
I'm not sure how you'd do this in a compiler-independent fashion. Would it be useful to provide a clear-on-free option when building the library?

I did try this:
```
#include <string.h>
#include <stdlib.h>

void clear_and_free(void *ptr, size_t size)
{
	memset(ptr, 0, size);
	asm volatile ("" ::: "memory");
	free(ptr);
}
```
and that worked with clang and gcc at least, but that seems pretty sketchy for a security-focused target.

**Comment by arichardson** [comment]
Some C libraries provide `explicit_bzero`, `memset_s` or the recent C23 `memset_explicit`, but I'm not sure if picolibc has any of these. There was some discussion on the LLVM mailing list about this earlier this year (https://discourse.llvm.org/t/implement-memset-explicit/77312/27) and LLVM libc added memset_explicit a memset+compiler barriers:
```
[[gnu::noinline]] LLVM_LIBC_FUNCTION(void *, memset_explicit,
                                     (void *dst, int value, size_t count)) {
  // Use the inline memset function to set the memory.
  inline_memset(dst, static_cast<uint8_t>(value), count);
  // avoid dead store elimination
  // The asm itself should also be sufficient to behave as a compiler barrier.
  asm("" : : "r"(dst) : "memory");
  return dst;
}
```

I think picolibc could do the same?

**Comment by asiekierka** [comment]
`memset_s` is part of C11 Annex K and `memset_explicit` is part of C23, so both appear in scope for picolibc; the former has an implementation already, but I'm not sure if the guarantee is upheld in all cases (f.e. with LTO involved) - it might need a compiler barrier added similarly to the above example.

**Comment by keith-packard** [comment]
I'm adding `memset_explicit` and including the memory barrier there. I've also added a barrier to `memset_s` in case people think that is also guaranteed to write to memory (the spec language is vague to my reading, but being safe is better than letting the compiler get away with hijinks),
