### ISSUE TITLE
Machine override of <sys/stdio.h>

### ISSUE THREAD

**Issue by stuarch** [picolibc/picolibc#88]
Hi,
I've seen there is a change that we can have machine overrides for `<sys/*.h>`, but `<sys/stdio.h>` seems missing for this since it's build alone under `newlib/stdio/sys/`, and the subdir wasn't applied the same change.
Will `<sys/stdio.h>` have the same change?

**Comment by keith-packard** [comment]
As you can see here, I've created PR #90 with a proposed fix. Please test that and see if it does what you need.

**Comment by stuarch** [comment]
Thanks, this is exactly what I need.
